version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app-container
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
    command: >
      python main.py
